services:
  quantum-mastermind-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      # CHANGÉ: REACT_APP_ → VITE_ pour Vite
      - VITE_API_URL=http://localhost:9000
    restart: unless-stopped
    networks:
      - quantum-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  quantum-network:
    driver: bridge
