version: '3.8'

services:
  quantum-mastermind-frontend:
    build: .
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    restart: unless-stopped
    networks:
      - quantum-network

networks:
  quantum-network:
    external: true
